### PR TITLE
fix: follow line height and opacity guidelines for text

### LINKED ISSUE #23: Text
[MD Docs Link](https://material.google.com/style/typography.html#)
We will also need to load Roboto typeface for IOS

### PR DESCRIPTION
**Pull request by satya164**
Fixes #23 

image

### CODE REVIEW

File: src/components/Typography/Headline.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 /* @flow */
 
-import withTheme from '../../core/withTheme';
-import fonts from '../../styles/fonts';
 import createStyledText from './createStyledText';
 
-const Subheading = createStyledText(fonts.regular, 24);
-
-export default withTheme(Subheading);
+export default createStyledText('Caption', {
```
Comment (ahmedlhanafy) [inline src/components/Typography/Headline.js]: @satya164 This should be `Subheader`

Comment (satya164) [inline src/components/Typography/Headline.js]: @ahmedlhanafy sorry will send another PR. Lost these files once and screwed up while recreating
